[project]
name = "excel-gantt-from-redmine"
version = "0.1.0"
description = "Generate excel gantt chart from redmine"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "python-redmine>=2.5.0",
]
